name: blogging_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  dotted_border: ^2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  fpdart: ^1.1.1
  get_it: ^8.0.3
  image_picker: ^1.1.2
  supabase_flutter: ^2.8.4
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
